version: 2.1

jobs:
  build:
    macos:
      xcode: 12.2.0
    steps:
      - checkout
      - run:
          name: Build TidepoolKit
          command: set -o pipefail && time xcrun xcodebuild -project 'TidepoolKit.xcodeproj' -scheme 'Shared' build -destination 'name=iPhone 8' build | xcpretty
      - run:
          name: Run TidepoolKit unit tests
          command: set -o pipefail && time xcrun xcodebuild -project 'TidepoolKit.xcodeproj' -scheme 'Shared' build -destination 'name=iPhone 8' test | xcpretty
      - run:
          name: Build TidepoolKit Example
          command: set -o pipefail && time xcrun xcodebuild -project 'TidepoolKit.xcodeproj' -scheme 'TidepoolKit Example' -destination 'name=iPhone 8' build CODE_SIGNING_ALLOWED=NO | xcpretty
